###
GET http://localhost:8080/
###
GET http://localhost:8080/words
###
GET http://localhost:8080/add
###
GET http://localhost:8080/addWord?word=apple
###
POST http://localhost:8080/addWord
Content-Type: application/x-www-form-urlencoded

word=zebra
